### ISSUE TITLE
Feature request: Need to detect if sync process is already running.

### ISSUE THREAD

**Issue by joshkerr** [cvockrodt/put.io-aria2c-downloader#2]
In order for this script to be useful running in a cron, you need to first detect that a sync isn't already happening. Otherwise, if you have a long list of files downloading and the cron fires, it will launch a second sync process. It should detect that there is a process already syncing and then shutdown.

**Comment by cvockrodt** [comment]
I had a [simple wrapper script](https://github.com/cvockrodt/put.io-aria2c-downloader/blob/1c68e2c26150c0b05c163b5b41ee056ca7b34669/is_putio_downloader_running) in a previous version but removed it in case people wanted to do things differently. I may put it back in, but you can see what it did in the mean time. Keep in mind it was a previous version so the click entry point isn't present
